# Generated by Django 3.1.5 on 2021-06-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('nationalcode', models.CharField(max_length=10)),
                ('doctorname', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('codes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
